### ISSUE TITLE
Excel file format

### ISSUE THREAD

**Issue by qcsui** [CopurOnur/BingMapsRestfullApi#1]
Love your code, Neat!

Can you give a example of Excel file? How should format of the Origin and Destination be?

**Comment by CopurOnur** [comment]
origin and destinations should be coordinates as float numbers. 2 columns is enough. first should contain the latitudes and the second should contain the longitudes. Each column should have a header. you can save the file as .xlsx then run the script. 
you should place the headers of latitude and longitude columns inside 

df=pd.DataFrame(data={"latitude":matrix["Header latitude"],"longitude":matrix["header longitude"]})
